spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000
  datasource:
    name: ranking
    url: jdbc:mysql://127.0.0.1:3306/ranking?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: just
    type: com.alibaba.druid.pool.DruidDataSource




#≈‰÷√mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wlxh.just.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl